import { Eye, RefreshCw } from "lucide-react";
import type { DocumentSource } from "../../types";
import { Badge } from "../common/Badge";

const statusTone = (status: DocumentSource["status"]) => status === "indexed" ? "green" : status === "failed" ? "red" : status === "pending_ingestion" ? "amber" : "slate";

export function DocumentTable({ documents, showActions = true }: { documents: DocumentSource[]; showActions?: boolean }) {
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-[0.12em] text-slate-500 dark:bg-slate-950"><tr>{["Document", "Department", "Access", "Version", "Status", "Last indexed", "Chunks", "Owner", ...(showActions ? ["Actions"] : [])].map((column) => <th key={column} className="px-4 py-3 font-bold">{column}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{documents.map((document) => <tr key={document.id} className="text-slate-700 hover:bg-slate-50/70 dark:text-slate-200 dark:hover:bg-slate-800/40"><td className="px-4 py-4"><p className="font-semibold text-slate-950 dark:text-white">{document.title}</p><p className="mt-0.5 text-xs text-slate-400">{document.fileType.toUpperCase()}</p></td><td className="px-4 py-4">{document.department}</td><td className="px-4 py-4"><Badge tone="purple">{document.accessLevel}</Badge></td><td className="px-4 py-4">{document.version}</td><td className="px-4 py-4"><Badge tone={statusTone(document.status)}>{document.status.replace("_", " ")}</Badge></td><td className="px-4 py-4 text-xs text-slate-500">{document.lastIndexedAt ? new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(document.lastIndexedAt)) : "Not indexed"}</td><td className="px-4 py-4">{document.chunkCount ?? 0}</td><td className="px-4 py-4">{document.owner}</td>{showActions && <td className="px-4 py-4"><div className="flex gap-1"><button className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800" title="View details"><Eye className="h-4 w-4" /></button><button className="rounded-lg p-2 text-slate-300" disabled title="Re-index is disabled in Phase 0-2"><RefreshCw className="h-4 w-4" /></button></div></td>}</tr>)}</tbody></table></div></div>;
}

