#!/usr/bin/env python3
"""Reset local runtime data after an explicit confirmation phrase."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Iterable

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from backend.config import settings


CONFIRMATION = "RESET_LOCAL_DATA"


def _children(path: Path) -> Iterable[Path]:
    return list(path.iterdir()) if path.exists() else []


def _remove(path: Path) -> None:
    if path.is_dir() and not path.is_symlink():
        for child in list(path.iterdir()):
            _remove(child)
        path.rmdir()
    else:
        path.unlink(missing_ok=True)


def reset_local_data(
    data_root: Path,
    *,
    include_sample_documents: bool = False,
) -> list[Path]:
    resolved = data_root.expanduser().resolve()
    if resolved == Path(resolved.anchor) or resolved.name != "data":
        raise ValueError("Reset is restricted to a directory named 'data'.")

    removed: list[Path] = []
    for database in (resolved / "app.db", resolved / "app.db-shm", resolved / "app.db-wal"):
        if database.exists():
            _remove(database)
            removed.append(database)

    for directory_name in ("processed", "chroma", "archived"):
        directory = resolved / directory_name
        for child in _children(directory):
            if child.name == ".gitkeep":
                continue
            _remove(child)
            removed.append(child)

    raw = resolved / "raw"
    for child in _children(raw):
        if child.name == ".gitkeep":
            continue
        if not include_sample_documents and child.name.startswith("sample_"):
            continue
        _remove(child)
        removed.append(child)

    for directory_name in ("raw", "processed", "archived", "chroma", "backups"):
        (resolved / directory_name).mkdir(parents=True, exist_ok=True)
    return removed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--confirm",
        help=f"Required exact confirmation phrase: {CONFIRMATION}",
    )
    parser.add_argument(
        "--include-sample-documents",
        action="store_true",
        help="Also remove files generated by scripts/create_dummy_documents.py.",
    )
    args = parser.parse_args()
    if args.confirm != CONFIRMATION:
        print("No data was changed.")
        print(f"Re-run with --confirm {CONFIRMATION} after creating a backup.")
        return 2

    removed = reset_local_data(
        settings.sqlite_path.parent,
        include_sample_documents=args.include_sample_documents,
    )
    print(f"Reset complete. Removed {len(removed)} runtime paths.")
    print("Backups, source code, docs, .env.example, and sample documents were preserved.")
    if args.include_sample_documents:
        print("Sample documents were explicitly removed.")
    print("Run python scripts/init_db.py before restarting the backend.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
