import { BarChart3, Clock3, FileCheck2, MessageSquareText, ShieldAlert, ThumbsUp } from "lucide-react";
import { PageHeader } from "../components/common/PageHeader";
import { mockReport } from "../mocks/reports";

const cards = [
  { label: "Questions asked", value: mockReport.totalQuestions.toLocaleString(), icon: MessageSquareText, tone: "bg-indigo-50 text-indigo-600" },
  { label: "Answered with sources", value: mockReport.answeredWithSources.toLocaleString(), icon: FileCheck2, tone: "bg-emerald-50 text-emerald-600" },
  { label: "Refusals", value: mockReport.refusals.toString(), icon: ShieldAlert, tone: "bg-amber-50 text-amber-600" },
  { label: "Average latency", value: `${mockReport.averageLatencyMs} ms`, icon: Clock3, tone: "bg-sky-50 text-sky-600" },
];

export function ReportsPage() {
  return <div className="p-5 sm:p-7"><PageHeader title="Usage reports" description="Clearly marked mock analytics. No real user activity is represented." actions={<span className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-700">MOCK DATA</span>} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon, tone }) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></div><p className="mt-5 text-2xl font-bold text-slate-950 dark:text-white">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-brand-500" /><h2 className="font-bold text-slate-950 dark:text-white">Top departments queried</h2></div><div className="mt-5 space-y-4">{mockReport.topDepartments.map((department, index) => <div key={department}><div className="mb-1.5 flex justify-between text-sm"><span className="font-semibold text-slate-700 dark:text-slate-200">{department}</span><span className="text-slate-400">{42 - index * 9}%</span></div><div className="h-2 rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-2 rounded-full bg-brand-500" style={{ width: `${42 - index * 9}%` }} /></div></div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2"><ThumbsUp className="h-5 w-5 text-emerald-500" /><h2 className="font-bold text-slate-950 dark:text-white">Feedback summary</h2></div><div className="mt-6 flex items-center gap-6"><div className="flex h-24 w-24 items-center justify-center rounded-full border-[10px] border-emerald-100 text-xl font-bold text-emerald-600 dark:border-emerald-950">{mockReport.positiveFeedbackPercent}%</div><div><p className="font-semibold text-slate-800 dark:text-slate-200">Positive mock feedback</p><p className="mt-1 text-sm leading-6 text-slate-500">This widget is a visual placeholder until real feedback and audit storage are built.</p></div></div></section></div></div>;
}

